<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SimpleAuth.Model\SimpleAuth.Model.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Account\Login.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Pages\Account\Login.cshtml" />
    </ItemGroup>

</Project>
